### ISSUE TITLE
Any reason for company-lsp-async to exist?

### ISSUE THREAD

**Issue by Sarcasm** [tigersoldier/company-lsp#19]
Hello,

Great package, thank you for that!

I was wondering why `company-lsp-async` existed, and why it default to `nil`?

In my mind, async backend is a 100% positive feature, and the only reason to not be have it would be that the framework used does not support asynchronous completion.

**Comment by sebastiencs** [comment]
I've introduced this variable at the time async operations were still experimental with `lsp-mode`

I wanted to change the default but it seems that async completion isn't always the best choice: https://github.com/tigersoldier/company-lsp/pull/14

**Comment by Sarcasm** [comment]
Thanks for the information, I'm also on Emacs 25, and I'm not sure to understand the issue @tigersoldier describes, I did not notice anything wrong when using async with cquery:
>  On emacs 25 when typing quickly the asynchronous function isn't called even if the responses are already there.
> Not sure if it's the same as in Emacs 26.
> If it is, I'd like to keep synchronized completion the default value.
> -- https://github.com/tigersoldier/company-lsp/pull/14#issuecomment-348858522

I'm thinking, if the issue happens only when the results are already available, `candidates` could check if the results are available, return them immediately if that's the case, and otherwise do the async call.

@dgutov: does the issue described rings a bell?

On a sidenote, looking again at the current implementation, I'm slightly surprised by what async means:

https://github.com/tigersoldier/company-lsp/blob/0f750d4cbde7063472b1f25b7cef7e632ae307cb/company-lsp.el#L308-L323

If would have expected candidates to be `:async` only if `if company-lsp-async` is set to `t`, but here the calls are always declared `:async`.

I expected:
- if candidates already cached, return candidates
- else if `company-lsp-async`, return `(:async async-handler)`
- else, return candidates synchronously

And ideally, if the issue described in #14, is not really an issue, I would just have:
- if candidates already cached, return candidates
- else, return `(:async async-handler)`

**Comment by dgutov** [comment]
@Sarcasm 

> does the issue described rings a bell?

**Comment by tigersoldier** [comment]
My personal test result is that enabling async completion makes completion less responsible for the languages that have fast servers. Basically the candidates are displayed only when you stop typing. Because of this reason I didn't set async as the default behavior.

We can possibly have an alist to map major modes or LSP client names to different defaults values, but I need your help because I don't have much experience on other language servers other than the one I wrote.

**Comment by tigersoldier** [comment]
After trying async again the experience was better. The completion flickers instead of delayed too much. However it's still not as good as synchronous completion.

![async-vs-sync](https://user-images.githubusercontent.com/226229/35606907-75c2804c-0606-11e8-90e5-611b41088ebd.gif)

(Note: the performance for async completion was better when not recording screencast, but there are still noticeable differences)

@Sarcasm About the implementation, yes it can be improved for the synchronized or cached case. However it doesn't change the behavior that much because company still calls :async right away:

https://github.com/company-mode/company-mode/blob/d789f2643c11f7c53fc47ed9d9b271bb6f6718a3/company.el#L918-L930

**Comment by dgutov** [comment]
Async + fuzzy can lead to flickers, that's a known problem, unfortunately.

> company still calls :async right away

That's true (for now, at least). But you've linked to a wrong function.

**Comment by Sarcasm** [comment]
I did not see the flicker in the gif, and the main difference I see is that after a trigger character, the dot, in sync mode the completion appears directly, while in async mode the completion doesn't appear until a few characters are typed (after a slight break). Which make sense I assume, if you type, that is you know what you want, the completion does not get in the way, and when you are stuck/need help, it appears.

But still, I understand why sync could be useful, I'm just wondering what this "flicker" is.

**Comment by dgutov** [comment]
> the main difference I see is that after a trigger character, the dot, in sync mode the completion appears directly, while in async mode the completion doesn't appear until a few characters are typed (after a slight break)

It's pretty weird. Completions after dot should appear pretty much after the same time. `company-idle-delay` works the same, and the time to wait for the response shouldn't be different. The only way for this to happen is if the user has typed the next character before the response was received. But then the behavior is an improvement (over waiting for a frozen UI).

> just wondering what this "flicker" is

I don't see it here either. It happens when async and no-cache are combined: https://github.com/company-mode/company-mode/issues/654

**Comment by Sarcasm** [comment]
Thank you Dmitry for your enlightening answer. 

So, could that be that the flicker @tigersoldier reported is because it sets `company-idle-delay` to 0?

https://github.com/tigersoldier/dotspacemacs/blob/b4e08fb09be25bb02812279075f170ccca1b9ae7/myconfigs/packages.el#L79

In which case, maybe recommend that people using a null idle delay, also force LSP to be synchronous.
And default company-lsp-async to `t`, as it should play well with standard company-mode in its default configuration.

**Comment by dgutov** [comment]
> could that be that the flicker @tigersoldier reported is because it sets company-idle-delay to 0?

Hopefully not. We're coercing such values to 0.01 anyway, see `company--idle-delay`.

You realize that null (nil) idle delay means no automatic completion, right?

**Comment by Sarcasm** [comment]
> You realize that null (nil) idle delay means no automatic completion, right?

I did not.
Sorry, when I said a "null idle delay", I was thinking about `0` not `nil`.

**Comment by tigersoldier** [comment]
Thanks for the information. Let me re-evaluate async with higher idle delay.

The flicker didn't happen when recording, it's worse - async is less responsive than sync. The GIF frame is too low. I uploaded the video to YouTube, hopefully it's more clear.

https://youtu.be/oOhve5m255o

**Comment by tigersoldier** [comment]
One explanation why async performance is so bad on my machine is that Emacs doesn't call process  filters that often when you are typing. I logged some debug message and I observe responses from the server got dispatched to elisp callback functions in batches after a few consecutive key strokes. On sync mode the client waits for the responses so they are delivered on time.

**Comment by Sarcasm** [comment]
Oh, so the sync mode basically help lsp mode synchronize, and not accumulate too much unnecessary work?

Is this related to this PR and issues referenced there?
- https://github.com/emacs-lsp/lsp-mode/pull/239

**Comment by dgutov** [comment]
> Sorry, when I said a "null idle delay", I was thinking about 0 not nil.

I see. Well, I generally recommend against 0 (or values close to it), except for well-tuned backends, such as ycmd (which does some extra caching to keep afloat), exactly because it causes the maximum possible background CPU usage. Synchronous mode helps somewhat, but it still taxes the CPU a lot more than it really has to.

I'm really unconvinced that the synchronous mode is the proper way to solve this problem. But if there's something we can do to improve this on Company's side, I'm all ears.

I think ycmd has some internal queue, as well as an ability to abort processing of out-of-date requests early. Or if it doesn't, this might be the best server-based solution anyway.

**Comment by Sarcasm** [comment]
IMHO, the issue is on the communication with the server (lsp-mode probably), it could be a quality of implementation issue.
In irony-mode, on the Elisp side, I made sure not to accumulate too many pending requests.
Looks like lsp-mode tried too, ran into issues, used some other methods but I have the feeling it may not be sorted out yet, understandably.

**Comment by dgutov** [comment]
Hmm, so you're saying that a queue with max_active_requests=1 and automatic discarding of yet-unsent requests and a new one comes along mostly solves this problem?

Might be an okay approach: at worst, the user only has to wait for two requests to complete, one after another.

**Comment by tigersoldier** [comment]
After playing with async completion for a while,  I identified two bugs in cache handling. Will work on a fix and see if it improves the experience.

> In irony-mode, on the Elisp side, I made sure not to accumulate too many pending requests.

Can you share your strategy how to avoid accumulating too many pending requests? I have some ideas in mind, but each has its own flaws:
 * Do not send new request until the previous one returns - This is likely result in staled results. This can be improved if we ignore the previous request and force sending a new one on idle. However I have no idea how to detect if it's an idle completion or not.
 * Cancel the previous pending requests. LSP has a [$/cancelRequest](https://microsoft.github.io/language-server-protocol/specification#cancelRequest) for this purpose. However it may not be implemented in some servers.

**Comment by dgutov** [comment]
> This is likely result in staled results

Worst case, you get double the latency.

I don't see why you need to know whether completion is idle or not.

**Comment by tigersoldier** [comment]
Asynchronous completion is the default behavior as of b58c8c4cbfb0e01ee9020f09dfd25cfadda58cc1. I'm keeping this option just in case there are unknown regressions.

**Comment by Sarcasm** [comment]
Great, thank you for following up on company-mode :+1:
