### ISSUE TITLE
It doesn't use completion item's label as completion labels

### ISSUE THREAD

**Issue by kaiwk** [tigersoldier/company-lsp#29]
<img width="747" alt="screen shot 2018-03-27 at 2 20 58 pm" src="https://user-images.githubusercontent.com/10190397/37950153-1b45f884-31ca-11e8-87a4-aaaf3b7fd522.png">

After I hit return key, it will give `render` rather than `render(request, template_name ..... )`.

I use emacs 25+ and lsp-python mode. Any help?

**Comment by tigersoldier** [comment]
This is working as intended. The python language server sends the completion item with `insertText` set to `render`:

```json
{
 "label": "render(request, template_name, context, content_type, status, using)", 
 "kind": 3,
 "detail": "__main__",
 "documentation": "render(request, template_name, context=None, content_type=None,\nstatus=None, using=None)\n\nReturns a HttpResponse whose content is filled with the result of calling\ndjango.template.loader.render_to_string() with the passed arguments.",
 "sortText": "arender",
 "insertText": "render"
}
```

This means the python language server wants you to get `render` instead of `render(request, template_name, context, content_type, status, using)`.  You probably expect it completes with the arguments and allows you to TAB through the arguments to specify their values, like the demo GIF in our readme. To achieve that, you can either:

 - File a bug against [palantir/python-language-server](https://github.com/palantir/python-language-server) for supporting InsertTextFormat.Snippet. This means the returned completion item should have `"insertTextFormat": 2` and `"insertText": "render(${1:request}, ${2:template_name}, ${3:context}, ${4: content_type}, ${5:status}, ${6:using})$0"`. See the definition of `CompletionItem` and `InsertTextFormat` [here](https://microsoft.github.io/language-server-protocol/specification) for details.
 - Implement your own elisp function to extract completion snippets. See [our readme](https://github.com/tigersoldier/company-lsp#defining-completion-snippet-for-a-certain-language)  for more details. It's highly discouraged unless the owners of Python language server refuse to support snippets or you can't wait for them to implement snippets support.

**Comment by kaiwk** [comment]
Thank you! That's very informative. Anyway, since I can make use of `eldoc` to lookup function's parameters, so maybe it's not a very urgent problem to me.

**Comment by cslux** [comment]
@kaiwk Has been implemented in pyls now https://github.com/palantir/python-language-server/commit/ee71c1ddddb769ca04cf59bac63036554283d8b9.
