### ISSUE TITLE
Company completes inside comments and strings

### ISSUE THREAD

**Issue by CSRaghunandan** [tigersoldier/company-lsp#44]
I've had this problem for Python and Rust modes when using `lsp-mode`. Not sure if this belongs to `company-lsp` or should I make an issue in the language specific LSP clients for lsp-mode?

**Comment by wyuenho** [comment]
Does #47 solve your problem?

**Comment by tigersoldier** [comment]
#47 disables completion for comments or strings for now. In the future I may add options to turn it on for certain languages clients that provide capability for completing comments or strings.

**Comment by wbthomason** [comment]
Sorry to necro an old issue, but I seem to still be getting this problem with `cquery` and `company-lsp`, despite #47. I'm not sure if the problem is here or in `cquery`, but this seems relevant.

Apologies if this is the wrong place, but do you have any suggestions for debugging this? Can anyone else reproduce the issue?

I'm in Emacs 26.1 with the latest `company-lsp` from MELPA.

**Comment by wyuenho** [comment]
Your other company backends and packages may be causing this. Try isolating them one by one and find out which it is.

**Comment by wbthomason** [comment]
Previously, `company-diag` had pointed at `company-lsp` as the culprit. I'm seeing `company-capf` as the troublemaker now, though, so maybe it was a transient issue? Sorry for the spam; I'll open a new issue if it _does_ turn out to be `company-lsp`.
