### ISSUE TITLE
Enhancement: fuzzy matching 

### ISSUE THREAD

**Issue by yyoncho** [tigersoldier/company-lsp#64]
Support for fuzzy matching, screenshot from vscode:
![image](https://user-images.githubusercontent.com/13259670/46971419-8f3b5d80-d0c4-11e8-8077-1ed6cb1c6ce5.png)

**Comment by dgutov** [comment]
> whether it is already supported

Sure. Use `no-cache` and return a list of chunks in `match`.

**Comment by MaskRay** [comment]
I have long ago a fuzzy-match PR in [swiper](https://github.com/abo-abo/swiper/pull/1518), but never have time to finish the interaction part.

The algorithm was originally implemented in C++ https://github.com/MaskRay/ccls/blob/master/src/fuzzy_match.cc (which was adapted from clangd's) and the translation to elisp harms the readability a lot.. Will appreciate if someone can pick it up and adopt similar idea if that turns out to be useful (I had studied fzf and similar tools and this current form was my final conclusion)

**Comment by tigersoldier** [comment]
@yyoncho Thanks for the clarification and sorry for late response. I don't remember seeing the "Alternatively" part when I started company-lsp. That's the only reason why it's not supported.

@dgutov Looks like this capability was added by company-mode/company-mode#798. Any idea how to do compatibility checks to ensure company-mode supports list for `match`?

**Comment by tigersoldier** [comment]
@yyoncho @dgutov  interested in reviewing #65 ?

**Comment by dgutov** [comment]
> Any idea how to do compatibility checks to ensure company-mode supports list for match?

Guess I'll need to cut a release first.

> interested in reviewing #65 ?

Looks okay to me. As long as it works. :)

**Comment by dgutov** [comment]
> Guess I'll need to cut a release first.

And done.
